#!/bin/sh
#
# Setting up networking
#

case "$1" in
  start)
    echo "Running ifup -a"
    /sbin/ifup -a
    ;;

  stop)
    echo "Running ifdown -a"
    /sbin/ifdown -a
    ;;

  restart)
    echo "Restarting networking"
    /sbin/ifup -a
    /sbin/ifdown -a
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
