workdir: /apps
vsock_port: 1337
crypto:
  cipher: Aes
  iv_mode: Plain
  block_mode: Cbc
  iv_offset: 0
launcher:
  Oci:
    RaTLS:
      root_ca: /usr/share/app-manager/ratls/root-ca.crt
      token_resolver: rsi
keysealing: 
  HkdfSha256:
    RsiSealingKey:
      flags:
autostartall: true
ca_pub: /usr/share/app-manager/ca/root-ca.pub
extend: rem0
