workdir: /apps
vsock_port: 1337
crypto:
  cipher: Aes
  iv_mode: Plain
  block_mode: Cbc
  iv_offset: 0
launcher:
  Oci:
    RaTLS:
      root_ca: /usr/share/app-manager/ratls/root-ca.crt
      token_resolver: 
        file: /usr/share/app-manager/ratls/token.bin
keysealing: 
  HkdfSha256:
    StubbedHex: AABB
autostartall: true
